"""Ports; no persistence or transport leaks into the domain."""
from typing import Protocol, Iterable
from uuid import UUID
from .models import *

class CoreApi(Protocol):
    def authorize(self, user_id: str, organization_id: str, permission: str, location_id: str | None = None) -> dict: ...
    def validate_identity(self, organization_id: str, user_id: str, external_subject: str) -> dict: ...
    def link_identity(self, actor_user_id: str, organization_id: str, person_id: str, user_id: str, external_subject: str) -> dict: ...
    def unlink_identity(self, actor_user_id: str, organization_id: str, person_id: str) -> dict: ...

class AuditSink(Protocol):
    def append(self, event: AuditEvent) -> None: ...

class PersonStore(Protocol):
    def create_person(self, person: Person, link: OrganizationLink) -> Person: ...
    def get_person(self, organization_id: str, person_id: UUID) -> Person | None: ...
    def list_persons(self, organization_id: str, limit: int, after: UUID | None = None) -> list[Person]: ...
    def update_person(self, person: Person, expected_version: int) -> Person: ...
    def add_identifier(self, identifier: Identifier, expected_version: int) -> Identifier: ...
    def list_identifiers(self, organization_id: str, person_id: UUID) -> list[Identifier]: ...
    def add_contact(self, contact: Contact, expected_version: int) -> Contact: ...
    def list_contacts(self, organization_id: str, person_id: UUID) -> list[Contact]: ...
    def candidates(self, organization_id: str, keys: set[str], limit: int) -> list[tuple[Person, str]]: ...
